version: "2"
services:

 mysqldb:
  image: mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: root123
   MYSQL_DATABASE: springbootdb
  ports:
   - 3306:3306
  network_mode: host
  hostname: localhost
  volumes:
   - data:/var/lib/mysql  

 mongo:
  image: mongo:3.4-jessie
  restart: always
  ports:
   - 27017:27017
  network_mode: host
  expose:
   - 27017
  hostname: localhost
  volumes:
   - ./data/db:/data/db

 apigateway:
  image: zuul-service
  build: zuul-gatewayservice/
  restart: always
  network_mode: host
  depends_on:
   - eurekaserver
  ports:
   - 8092:8092
  expose:
   - 8092

 eurekaserver:
  image: eureka-servcie:latest
  build: eureka-server/
  restart: always
  network_mode: host
  ports:
   - 9091:9091
  expose:
   - 9091

 configserver:
  image: config-servcie:latest
  build: config-server/
  restart: always
  network_mode: host
  ports:
   - 8888:8888
  expose:
   - 8888

 userlogin:
  image: userlogin-service
  build: userlogin/
  restart: always
  network_mode: host
  depends_on:
   - eurekaserver
   - apigateway
   - configserver
   - mysqldb
   - kafka
  ports:
   - 8096:8096
  expose:
   - 8096

 userreg:
  image: userreg-service
  build: userreg/
  restart: always
  network_mode: host
  depends_on:
   - eurekaserver
   - apigateway
   - configserver
   - mongo
   - kafka
  ports:
   - 8093:8093
  expose:
   - 8093

 kafka:
  image: landoop/fast-data-dev:latest
  ports:
   - 2181:2181
   - 3030:3030
   - 9092:9092
   - 8081:8081
   - 8082:8082
   - 8083:8083
  container_name: kafka_docker
  network_mode: host
  hostname: localhost
  restart: always
  volumes:
   - ./Desktop/DockerKafka:/data/kafka

volumes:
 data:




