version: "2"
services:

  apigateway:
    image: zuul-service
    build: zuul-gatewayservice/
    restart: always
    network_mode: host
    depends_on:
    - eurekaserver
    ports:
    - 8092:8092
    expose:
    - 8092

  eurekaserver:
    image: eureka-servcie:latest
    build: eureka-server/
    restart: always
    network_mode: host
    ports:
    - 9091:9091
    expose:
    - 9091

  configserver:
      image: config-servcie:latest
      build: config-server/
      restart: always
      network_mode: host
      ports:
      - 8888:8888
      expose:
      - 8888

  recommendation:
    image: recommendation-service:latest
    build: recommendation/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
      - configserver
      - neo4j
    ports:
      - 8084:8084
    expose:
      - 8084

  neo4j:
      image: neo4j:latest
      ports:
        - 7474:7474
        - 7687:7687
      container_name: neo4j_docker
      network_mode: host
      hostname: localhost
      restart: always
      volumes:
        - ./Desktop/neo4j:/data/db




