version: "2"
services:

  apigateway:
    image: zuul-service
    build: zuul-gatewayservice/
    restart: always
    network_mode: host
    depends_on:
    - eurekaserver
    ports:
    - "8092:8092"
    expose:
    - 8092

  eurekaserver:
    image: eureka-servcie:latest
    build: eureka-server/
    restart: always
    network_mode: host
    ports:
    - "9091:9091"
    expose:
    - 9091

  configserver:
      image: config-servcie:latest
      build: config-server/
      restart: always
      network_mode: host
      ports:
      - 8888:8888
      expose:
      - 8888
  searchservice:
      image: search-service:latest
      build: searchservice/
      restart: always
      network_mode: host
      ports:
      - 8095:8095
      expose:
      - 8095
      depends_on: 
      - mongodb
      - configserver
      - eurekaserver
  mongodb:
      image: mongo:3.4-jessie
      container_name: mongodb
      volumes:
      - ./data/db:/data/db
      ports:
      - 27017:27017
      network_mode: host
      hostname: localhost
      restart: always
    
volumes:
 data:



  pie-admin-service:
      image: pie-admin-service:1.0.0
      build: admin/
      ports:
      - 8055:8055
      network_mode: host




